#!/usr/bin/env bash

set -euo pipefail

help() {
  echo "용례"
  echo "git csv release/230222 | grep --invert 'shiftupcorp/patch/' > /mnt/c/Users/SHIFTUP/Downloads/result.csv"
  echo "설명 release/230222 브랜치와 main을 비교해서 (서버 패치 pr들은 제외하고) csv 파일로 만듭니다"
}

while getopts ":h" option; do
   case $option in
      h) # display Help
         help
         exit;;
   esac
done

b1=$1
b2="HEAD"

format='${author},${jira},${pr},${summary}'
header='체리픽됨,저자확인,저자,jira,pr,요약'
echo "$header"
while read -r a b; do
  if [ "$a" = "=" ]; then
    a="TRUE"
  elif [ "$a" = ">" ]; then
    a="FALSE"
  else
    a="#NULL"
  fi
  echo "$a,FALSE,$(git meta "$b" -f "$format")"
done < <(git compare "$b1" "$b2" | sort -k 1)